//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 gWorld;                   // Offset:    0 Size:    64 [unused]
//   uint gMaterialIndex;               // Offset:   64 Size:     4
//   uint pad1;                         // Offset:   68 Size:     4 [unused]
//   uint pad2;                         // Offset:   72 Size:     4 [unused]
//   uint pad3;                         // Offset:   76 Size:     4 [unused]
//
// }
//
// cbuffer cbPerPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64 [unused]
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  448
//       float FalloffStart;            // Offset:  460
//       float3 Direction;              // Offset:  464
//       float FalloffEnd;              // Offset:  476
//       float3 Position;               // Offset:  480
//       float SpotPower;               // Offset:  492
//       float4x4 ShadowViewProj;       // Offset:  496
//       float4x4 ShadowTransform;      // Offset:  560
//
//   } gLights[16];                     // Offset:  448 Size:  2816
//
// }
//
// Resource bind info for gMaterialData
// {
//
//   struct MaterialData
//   {
//       
//       float4 DiffuseAlbedo;          // Offset:    0
//       float3 FresnelR0;              // Offset:   16
//       float Roughness;               // Offset:   28
//       uint DiffuseMapIndex;          // Offset:   32
//       uint MatPad0;                  // Offset:   36
//       uint MatPad1;                  // Offset:   40
//       int hasNormalMap;              // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      ID      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- ------- -------------- ------
// gLinearSample                     sampler      NA          NA      S0             s0      1 
// gCubeMap                          texture  float4        cube      T0             t0      1 
// gMaterialMap                      texture  float4          2d      T1             t2      3 
// gMaterialData                     texture  struct         r/o      T2      t0,space1      1 
// cbPerObject                       cbuffer      NA          NA     CB0            cb0      1 
// cbPerPass                         cbuffer      NA          NA     CB1            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
// TANGENT                  0   xyz         4     NONE   float   xyz 
// Binormal                 0   xyz         5     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_1
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[0:0][5], immediateIndexed, space=0
dcl_constantbuffer CB1[1:1][30], immediateIndexed, space=0
dcl_sampler S0[0:0], mode_default, space=0
dcl_resource_texturecube (float,float,float,float) T0[0:0], space=0
dcl_resource_texture2d (float,float,float,float) T1[2:4], space=0
dcl_resource_structured T2[0:0], 48, space=1
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xy
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.xyz
dcl_output o0.xyzw
dcl_temps 10
dcl_indexableTemp x0[3], 4
//
// Initial variable locations:
//   v0.x <- pin.PosH.x; v0.y <- pin.PosH.y; v0.z <- pin.PosH.z; v0.w <- pin.PosH.w; 
//   v1.x <- pin.PosW.x; v1.y <- pin.PosW.y; v1.z <- pin.PosW.z; 
//   v2.x <- pin.NormalW.x; v2.y <- pin.NormalW.y; v2.z <- pin.NormalW.z; 
//   v3.x <- pin.TexCoord.x; v3.y <- pin.TexCoord.y; 
//   v4.x <- pin.TangentW.x; v4.y <- pin.TangentW.y; v4.z <- pin.TangentW.z; 
//   v5.x <- pin.BitangentW.x; v5.y <- pin.BitangentW.y; v5.z <- pin.BitangentW.z; 
//   o0.x <- <PS return value>.x; o0.y <- <PS return value>.y; o0.z <- <PS return value>.z; o0.w <- <PS return value>.w
//
#line 55 "C:\gamedev\DX12Renderer\dx12\DX12HelloWorld\Shaders\color_SD.hlsl"
ld_structured r0.x, CB0[0][4].x, l(12), T2[0].xxxx  // r0.x <- matData.DiffuseAlbedo.w
ld_structured r1.x, CB0[0][4].x, l(16), T2[0].xxxx  // r1.x <- matData.FresnelR0.x
ld_structured r1.y, CB0[0][4].x, l(20), T2[0].xxxx  // r1.y <- matData.FresnelR0.y
ld_structured r1.z, CB0[0][4].x, l(24), T2[0].xxxx  // r1.z <- matData.FresnelR0.z
ld_structured r0.y, CB0[0][4].x, l(28), T2[0].xxxx  // r0.y <- matData.Roughness
ld_structured r0.z, CB0[0][4].x, l(32), T2[0].xxxx  // r0.z <- matData.DiffuseMapIndex
ld_structured r0.w, CB0[0][4].x, l(44), T2[0].xxxx  // r0.w <- matData.hasNormalMap

#line 57
dp3 r2.x, v2.xyzx, v2.xyzx
rsq r2.x, r2.x
mul r2.xyz, r2.xxxx, v2.xyzx  // r2.x <- pin.NormalW.x; r2.y <- pin.NormalW.y; r2.z <- pin.NormalW.z

#line 59
ine r0.w, l(0, 0, 0, 0), r0.w
if_nz r0.w

#line 61
  mov r3.xyz, r2.xyzx  // r3.x <- N.x; r3.y <- N.y; r3.z <- N.z

#line 62
  dp3 r0.w, v4.xyzx, r3.xyzx
  mul r4.xyz, r3.xyzx, r0.wwww
  mov r4.xyz, -r4.xyzx
  add r4.xyz, r4.xyzx, v4.xyzx
  dp3 r0.w, r4.xyzx, r4.xyzx
  rsq r0.w, r0.w
  mul r4.xyz, r0.wwww, r4.xyzx  // r4.x <- T.x; r4.y <- T.y; r4.z <- T.z

#line 63
  dp3 r0.w, v5.xyzx, r3.xyzx
  mul r5.xyz, r3.xyzx, r0.wwww
  mov r5.xyz, -r5.xyzx
  add r5.xyz, r5.xyzx, v5.xyzx
  dp3 r0.w, r5.xyzx, r5.xyzx
  rsq r0.w, r0.w
  mul r5.xyz, r0.wwww, r5.xyzx  // r5.x <- B.x; r5.y <- B.y; r5.z <- B.z

#line 65
  mov r6.x, r4.x  // r6.x <- TBN._m00
  mov r6.y, r5.x  // r6.y <- TBN._m10
  mov r6.z, r3.x  // r6.z <- TBN._m20
  mov r7.x, r4.y  // r7.x <- TBN._m01
  mov r7.y, r5.y  // r7.y <- TBN._m11
  mov r7.z, r3.y  // r7.z <- TBN._m21
  mov r3.x, r4.z  // r3.x <- TBN._m02
  mov r3.y, r5.z  // r3.y <- TBN._m12
  mov r3.z, r3.z  // r3.z <- TBN._m22

#line 66
  mov r0.w, l(1)
  iadd r0.w, r0.w, r0.z
  sample r4.xyz, v3.xyxx, T1[r0.w + 2].xyzw, S0[0]
  mov r4.xyz, r4.xyzx  // r4.x <- normalMap.x; r4.y <- normalMap.y; r4.z <- normalMap.z

#line 67
  mul r4.xyz, r4.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000)
  mov r5.xyz, l(-1.000000,-1.000000,-1.000000,-0.000000)
  add r4.xyz, r4.xyzx, r5.xyzx

#line 68
  dp3 r2.x, r4.xyzx, r6.xyzx
  dp3 r2.y, r4.xyzx, r7.xyzx
  dp3 r2.z, r4.xyzx, r3.xyzx

#line 69
endif 

#line 72
mov r3.xyz, -v1.xyzx
add r3.xyz, r3.xyzx, CB1[1][24].xyzx
dp3 r0.w, r3.xyzx, r3.xyzx
rsq r0.w, r0.w
mul r3.xyz, r0.wwww, r3.xyzx  // r3.x <- viewDir.x; r3.y <- viewDir.y; r3.z <- viewDir.z

#line 73
sample r4.xyz, v3.xyxx, T1[r0.z + 2].xyzw, S0[0]
mov r4.xyz, r4.xyzx  // r4.x <- diffuse.x; r4.y <- diffuse.y; r4.z <- diffuse.z

#line 75
mov r0.y, -r0.y
add r1.w, r0.y, l(1.000000)  // r1.w <- shininess

#line 76
mov r1.xyz, r1.xyzx  // r1.x <- mat.FresnelR0.x; r1.y <- mat.FresnelR0.y; r1.z <- mat.FresnelR0.z
mov r1.w, r1.w  // r1.w <- mat.Shininess
mov r4.xyz, r4.xyzx  // r4.x <- mat.DiffuseAlbedo.x; r4.y <- mat.DiffuseAlbedo.y; r4.z <- mat.DiffuseAlbedo.z

#line 78
mov r0.yzw, l(0,1.000000,1.000000,1.000000)  // r0.y <- shadowFactor.x; r0.z <- shadowFactor.y; r0.w <- shadowFactor.z

#line 80
nop 
mov x0[0].xyz, CB1[1][28].xyzx
mov x0[2].xyz, CB1[1][29].xyzx
mov r1.xyzw, r1.xyzw
mov r4.xyz, r4.xyzx
mov r2.xyz, r2.xyzx
mov r3.xyz, r3.xyzx
mov r0.yzw, r0.yyzw

#line 87 "C:\gamedev\DX12Renderer\dx12\DX12HelloWorld\Shaders\inc\LightingUtils.hlsli"
mov r5.xyz, l(0,0,0,0)  // r5.x <- result.x; r5.y <- result.y; r5.z <- result.z

#line 92
nop 
mov r6.xyz, x0[0].xyzx
mov r7.xyz, x0[2].xyzx
mov r1.xyzw, r1.xyzw
mov r4.xyz, r4.xyzx
mov r2.xyz, r2.xyzx
mov r3.xyz, r3.xyzx

#line 38
dp3 r2.w, r7.xyzx, r7.xyzx
rsq r2.w, r2.w
mul r7.xyz, r2.wwww, r7.xyzx
mov r7.xyz, -r7.xyzx  // r7.x <- lightDir.x; r7.y <- lightDir.y; r7.z <- lightDir.z

#line 39
dp3 r2.w, r7.xyzx, r2.xyzx
max r2.w, r2.w, l(0.000000)
mul r6.xyz, r2.wwww, r6.xyzx  // r6.x <- lightStrength.x; r6.y <- lightStrength.y; r6.z <- lightStrength.z

#line 41
nop 
mov r6.xyz, r6.xyzx
mov r7.xyz, r7.xyzx
mov r2.xyz, r2.xyzx
mov r3.xyz, r3.xyzx
mov r4.xyz, r4.xyzx
mov r1.xyzw, r1.xyzw

#line 16
mul r1.w, r1.w, l(1024.000000)  // r1.w <- m

#line 17
mov r8.xyz, -r3.xyzx
dp3 r2.w, r8.xyzx, r2.xyzx
add r2.w, r2.w, r2.w
mov r2.w, -r2.w
mul r9.xyz, r2.wwww, r2.xyzx
add r8.xyz, r8.xyzx, r9.xyzx  // r8.x <- r.x; r8.y <- r.y; r8.z <- r.z

#line 18
sample r8.xyz, r8.xyzx, T0[0].xyzw, S0[0]
mov r8.xyz, r8.xyzx  // r8.x <- reflectColor.x; r8.y <- reflectColor.y; r8.z <- reflectColor.z

#line 19
nop 

#line 20
add r3.xyz, r7.xyzx, r3.xyzx
dp3 r2.w, r3.xyzx, r3.xyzx
rsq r2.w, r2.w
mul r3.xyz, r2.wwww, r3.xyzx  // r3.x <- halfVec.x; r3.y <- halfVec.y; r3.z <- halfVec.z

#line 21
mov r2.w, l(0.800000)  // r2.w <- specStrength

#line 22
dp3 r2.x, r2.xyzx, r3.xyzx
max r2.x, r2.x, l(0.000000)
log r2.x, r2.x
mul r1.w, r1.w, r2.x
exp r1.w, r1.w
mul r1.w, r2.w, r1.w
mul r2.xyz, r6.xyzx, r1.wwww  // r2.x <- specular.x; r2.y <- specular.y; r2.z <- specular.z

#line 24
mul r3.xyz, r4.xyzx, r6.xyzx
mov r4.xyz, -r3.xyzx
add r4.xyz, r4.xyzx, r8.xyzx
mul r1.xyz, r1.xyzx, r4.xyzx
add r1.xyz, r1.xyzx, r3.xyzx
add r1.xyz, r2.xyzx, r1.xyzx  // r1.x <- <BlinnPhong return value>.x; r1.y <- <BlinnPhong return value>.y; r1.z <- <BlinnPhong return value>.z

#line 41
mov r1.xyz, r1.xyzx  // r1.x <- <ComputeDirectionalLight return value>.x; r1.y <- <ComputeDirectionalLight return value>.y; r1.z <- <ComputeDirectionalLight return value>.z

#line 92
mul r0.yzw, r0.yyzw, r1.xxyz
add r0.yzw, r0.yyzw, r5.xxyz  // r0.y <- result.x; r0.z <- result.y; r0.w <- result.z

#line 110
mov r0.yzw, r0.yyzw  // r0.y <- <ComputeLighting return value>.x; r0.z <- <ComputeLighting return value>.y; r0.w <- <ComputeLighting return value>.z

#line 80 "C:\gamedev\DX12Renderer\dx12\DX12HelloWorld\Shaders\color_SD.hlsl"
mov r0.yzw, r0.yyzw  // r0.y <- directLight.x; r0.z <- directLight.y; r0.w <- directLight.z

#line 81
mov r0.yzw, r0.yyzw  // r0.y <- litColor.x; r0.z <- litColor.y; r0.w <- litColor.z

#line 83
mov r0.x, r0.x  // r0.x <- litColor.w

#line 85
mov o0.xyz, r0.yzwy
mov o0.w, r0.x
ret 
// Approximately 128 instruction slots used
