//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      ID      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- ------- -------------- ------
// gLinearSample                     sampler      NA          NA      S0             s0      1 
// gCubeMap                          texture  float4        cube      T0             t0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// POSITION                 0   xyz         1     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_1
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_sampler S0[0:0], mode_default, space=0
dcl_resource_texturecube (float,float,float,float) T0[0:0], space=0
dcl_input_ps linear v1.xyz
dcl_output o0.xyzw
dcl_temps 1
//
// Initial variable locations:
//   v0.x <- pin.PosH.x; v0.y <- pin.PosH.y; v0.z <- pin.PosH.z; v0.w <- pin.PosH.w; 
//   v1.x <- pin.PosL.x; v1.y <- pin.PosL.y; v1.z <- pin.PosL.z; 
//   o0.x <- <PS return value>.x; o0.y <- <PS return value>.y; o0.z <- <PS return value>.z; o0.w <- <PS return value>.w
//
#line 32 "C:\gamedev\DX12Renderer\dx12\DX12HelloWorld\Shaders\sky_SD.hlsl"
sample r0.xyzw, v1.xyzx, T0[0].xyzw, S0[0]
log r0.xyzw, r0.xyzw
mul r0.xyzw, r0.xyzw, l(2.200000, 2.200000, 2.200000, 2.200000)
exp o0.xyzw, r0.xyzw
ret 
// Approximately 5 instruction slots used
