//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbSettings
// {
//
//   int gBlurRadius;                   // Offset:    0 Size:     4
//   float w0;                          // Offset:    4 Size:     4
//   float w1;                          // Offset:    8 Size:     4
//   float w2;                          // Offset:   12 Size:     4
//   float w3;                          // Offset:   16 Size:     4
//   float w4;                          // Offset:   20 Size:     4
//   float w5;                          // Offset:   24 Size:     4
//   float w6;                          // Offset:   28 Size:     4
//   float w7;                          // Offset:   32 Size:     4
//   float w8;                          // Offset:   36 Size:     4
//   float w9;                          // Offset:   40 Size:     4
//   float w10;                         // Offset:   44 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      ID      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- ------- -------------- ------
// gInput                            texture  float4          2d      T0             t0      1 
// gOutput                               UAV  float4          2d      U0             u0      1 
// cbSettings                        cbuffer      NA          NA     CB0            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_1
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[0:0][3], immediateIndexed, space=0
dcl_resource_texture2d (float,float,float,float) T0[0:0], space=0
dcl_uav_typed_texture2d (float,float,float,float) U0[0:0], space=0
dcl_input vThreadIDInGroup.y
dcl_input vThreadID.xy
dcl_temps 4
dcl_indexableTemp x0[11], 4
dcl_tgsm_structured g0, 16, 266
dcl_thread_group 1, 256, 1
//
// Initial variable locations:
//   vThreadIDInGroup.x <- groupThreadID.x; vThreadIDInGroup.y <- groupThreadID.y; vThreadIDInGroup.z <- groupThreadID.z; 
//   vThreadID.x <- dispatchThreadID.x; vThreadID.y <- dispatchThreadID.y; vThreadID.z <- dispatchThreadID.z; 
//   x0 <- weights
//
#line 30 "C:\gamedev\DX12Renderer\dx12\DX12HelloWorld\Shaders\vertBlur_CS.hlsl"
mov x0[0].x, CB0[0][0].y
mov x0[1].x, CB0[0][0].z
mov x0[2].x, CB0[0][0].w
mov x0[3].x, CB0[0][1].x
mov x0[4].x, CB0[0][1].y
mov x0[5].x, CB0[0][1].z
mov x0[6].x, CB0[0][1].w
mov x0[7].x, CB0[0][2].x
mov x0[8].x, CB0[0][2].y
mov x0[9].x, CB0[0][2].z
mov x0[10].x, CB0[0][2].w

#line 32
ilt r0.x, vThreadIDInGroup.y, CB0[0][0].x
if_nz r0.x
  mov r0.x, CB0[0][0].x  // r0.x <- gBlurRadius

#line 34
  ineg r0.x, r0.x
  iadd r0.x, r0.x, vThreadID.y
  imax r0.y, r0.x, l(0)  // r0.y <- y

#line 35
  mov r1.x, vThreadIDInGroup.y
  mov r0.x, vThreadID.x
  mov r0.zw, l(0,0,0,0)
  ld r0.xyzw, r0.xyzw, T0[0].xyzw
  store_structured g0.x, r1.x, l(0), r0.x
  store_structured g0.x, r1.x, l(4), r0.y
  store_structured g0.x, r1.x, l(8), r0.z
  store_structured g0.x, r1.x, l(12), r0.w

#line 36
endif 

#line 39
ineg r0.x, CB0[0][0].x
iadd r0.x, r0.x, l(256)
ige r0.x, vThreadIDInGroup.y, r0.x
if_nz r0.x

#line 41
  iadd r0.x, vThreadID.y, CB0[0][0].x
  resinfo_uint r0.y, l(0), T0[0].xyzw
  mov r0.z, l(1)
  ineg r0.z, r0.z
  iadd r0.y, r0.z, r0.y
  umin r0.y, r0.y, r0.x  // r0.y <- y

#line 42
  imul null, r1.x, CB0[0][0].x, l(2)
  iadd r1.x, r1.x, vThreadIDInGroup.y
  mov r0.x, vThreadID.x
  mov r0.zw, l(0,0,0,0)
  ld r0.xyzw, r0.xyzw, T0[0].xyzw
  store_structured g0.x, r1.x, l(0), r0.x
  store_structured g0.x, r1.x, l(4), r0.y
  store_structured g0.x, r1.x, l(8), r0.z
  store_structured g0.x, r1.x, l(12), r0.w

#line 43
endif 

#line 46
iadd r0.x, vThreadIDInGroup.y, CB0[0][0].x
mov r0.yz, vThreadID.xxyx
resinfo_uint r1.xy, l(0), T0[0].xyzw
mov r1.zw, l(0,0,1,1)
ineg r1.zw, r1.zzzw
iadd r1.xy, r1.zwzz, r1.xyxx
umin r1.xy, r0.yzyy, r1.xyxx
mov r1.zw, l(0,0,0,0)
ld r1.xyzw, r1.xyzw, T0[0].xyzw
store_structured g0.x, r0.x, l(0), r1.x
store_structured g0.x, r0.x, l(4), r1.y
store_structured g0.x, r0.x, l(8), r1.z
store_structured g0.x, r0.x, l(12), r1.w

#line 48
sync_g_t

#line 50
mov r0.xyzw, l(0,0,0,0)  // r0.x <- blurColor.x; r0.y <- blurColor.y; r0.z <- blurColor.z; r0.w <- blurColor.w

#line 51
ineg r1.x, CB0[0][0].x  // r1.x <- i
mov r2.xyzw, r0.xyzw  // r2.x <- blurColor.x; r2.y <- blurColor.y; r2.z <- blurColor.z; r2.w <- blurColor.w
mov r1.y, r1.x  // r1.y <- i
loop 
  ige r1.z, CB0[0][0].x, r1.y
  breakc_z r1.z

#line 53
  iadd r1.z, vThreadIDInGroup.y, CB0[0][0].x
  iadd r1.z, r1.y, r1.z  // r1.z <- k

#line 54
  iadd r1.w, r1.y, CB0[0][0].x
  mov r1.w, x0[r1.w + 0].x
  ld_structured r3.x, r1.z, l(0), g0.xxxx
  ld_structured r3.y, r1.z, l(4), g0.xxxx
  ld_structured r3.z, r1.z, l(8), g0.xxxx
  ld_structured r3.w, r1.z, l(12), g0.xxxx
  mul r3.xyzw, r1.wwww, r3.xyzw
  add r2.xyzw, r2.xyzw, r3.xyzw

#line 55
  iadd r1.y, r1.y, l(1)
endloop 

#line 57
mov r0.xyzw, vThreadID.xyyy
store_uav_typed U0[0].xyzw, r0.xyzw, r2.xyzw

#line 58
ret 
// Approximately 82 instruction slots used
